# .github/workflows/main.yml

name: Build KivyMD Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install P4A dependencies
        run: |
          # تحديث النظام وتثبيت أدوات التطوير الأساسية المطلوبة لعملية التجميع على Ubuntu
          sudo apt update
          sudo apt install -y build-essential libssl-dev libffi-dev python3-dev zip unzip

      - name: Install Python requirements (Kivy, KivyMD, P4A, sh)
        run: |
          pip install kivy kivymd python-for-android pillow sh

      - name: Build APK with P4A (Single Line Command)
        run: python -m pythonforandroid.toolchain apk --requirements=python3,kivy,kivymd --private . --package=com.awa213.todo --name="MyTodoApp" --version=0.1 --arch=arm64-v8a,armeabi-v7a
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: KivyMD_Todo_APK
          path: bin/*.apk
